name:  Update Factbook v2021 (Download & Generate JSON)

on:
  schedule:
    # note: * is a special character in YAML so you have to quote this string
    #  see cron guru for more examples / help on syntax
    #    ->  https://crontab.guru/examples.html
    # - cron:  '0 22 1,15 * *'       #  every 1 & 15 of the month at 22:00 (utc?)
    #  note: change to weekly every thursday
    - cron:  '0 22 * * THU'       #  every thursday at 22:00 (utc?)
  workflow_dispatch:
    ### for testing / debugging allow "manual" start


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7' # Version range or exact version of a Ruby version to use, using semvers version range syntax.

    - name: Run install / adduser
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        gem install nokogiri --no-document
        # fix:  require nokogiri on demand only (nokogiri NOT used by apis only pages for now!!!)
        bundle install --gemfile=./2021/Gemfile
        yo -f ./2021/Flowfile.rb adduser

    - name: Run ssh_clone
      run:  yo -f ./2021/Flowfile.rb clone

    - name: Run download
      run:  yo -r ./2021/download.rb -f ./2021/Flowfile.rb download

    - name: Run generate json v1
      run:  yo -r ./2021/genjson.rb -f ./2021/Flowfile.rb json1

    - name: Run generate json v2
      run:  yo -r ./2021/genjson.rb -f ./2021/Flowfile.rb json2

    - name: Run generate profiles
      run:  yo -r ./2021/genprofiles.rb -f ./2021/Flowfile.rb profiles

    - name: Run ssh_push
      run:  yo -f ./2021/Flowfile.rb push
